### ISSUE TITLE
Add Poppins bold to the list of fonts available for body text

### ISSUE THREAD

**Issue by mollieru** [MutualAidNYC/wp-theme#45]
We're currently using H2 styles for the intro text atop each interior page. Per guidance from Rachel, this is an accessibility faux pas. 

The ideal is to be able to select Poppins from the list of available fonts for paragraph styles:
<img width="643" alt="Screen Shot 2020-05-13 at 10 56 25 AM" src="https://user-images.githubusercontent.com/3680494/81829588-0dfab580-9509-11ea-974e-29847c3546c3.png">

**Comment by ChaosExAnima** [comment]
@jffng - Do you know how to customize that? Didn't see it in the docs.

**Comment by jffng** [comment]
We can't add font families to those controls unfortunately because they are baked into CoBlocks: https://github.com/godaddy-wordpress/coblocks/blob/master/src/components/font-family/fonts.js

@ChaosExAnima we could add a pullquote block style variation?

However, why would we want to give people a way to make paragraphs look like headings? This just creates a different accessibility issue. If we're actually using the H2 styles for things ... other than headings, then the type styles should change:

<img width="481" alt="Screen Shot 2020-05-13 at 7 18 18 PM" src="https://user-images.githubusercontent.com/5375500/81875573-8d5ea800-954e-11ea-8e8f-81ca4546fe6c.png">

**Comment by ChaosExAnima** [comment]
@jffng - Oh, didn't realize this was a CoBlocks thing, I thought it was Core! Looking at the code, I did find a filter here: https://github.com/godaddy-wordpress/coblocks/blob/master/src/components/font-family/index.js#L40

Think we can use that approach?

Regarding the styles, that's a question for @mollieru I think :)
